
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Sep 09 14:48:13 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 48;
  public static final int CONST = 6;
  public static final int LPAREN = 39;
  public static final int SEMI = 35;
  public static final int GREATER = 26;
  public static final int CONTINUE = 15;
  public static final int LESS = 28;
  public static final int MINUS = 20;
  public static final int RPAREN = 40;
  public static final int AND = 30;
  public static final int EQUALTO = 24;
  public static final int OR = 31;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int INC = 33;
  public static final int MEANS = 43;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int IF = 7;
  public static final int DOT = 38;
  public static final int GREATEROREQ = 27;
  public static final int FINDANY = 17;
  public static final int BOOLEAN = 49;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 32;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int NUMBER = 46;
  public static final int MOD = 23;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int COLON = 36;
  public static final int FOREACH = 16;
  public static final int LBRACE = 44;
  public static final int ELSE = 5;
  public static final int LSQUARE = 41;
  public static final int READ = 11;
  public static final int RSQUARE = 42;
  public static final int WHILE = 8;
  public static final int NOTEQUALTO = 25;
  public static final int RBRACE = 45;
  public static final int LESSOREQ = 29;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int DEC = 34;
  public static final int PRINT = 10;
  public static final int FINDANDREPLACE = 18;
}

